### ISSUE TITLE
ClassCastException when converting variable types with netcdf4

### ISSUE THREAD

**Issue by Gnafu** [Unidata/thredds#1038]
Hi all,
I'm trying to convert a NetCDF file from here:
https://podaac.jpl.nasa.gov/dataset/JPL_OUROCEAN-L4UHfnd-GLOB-G1SST

The goal is to have a new NetCDF with all the variables in float type.

I used the following ncml to do the conversion:
https://raw.githubusercontent.com/geoserver/geoserver/master/doc/en/user/source/community/netcdf-ghrsst/artifacts/ghrsst.ncml

The command I used is:
`java -Xmx2g -classpath ./netcdfAll-4.6.11.jar ucar.nc2.dataset.NetcdfDataset -in test_input.ncml -out all_float.nc -netcdf4`

But the process fails with the following message:
```
NetcdfDatataset read from test?input.ncml write to all_float.nc Exception in thread "main" java.lang.ClassCastException: [I cannot be cast to [F
        at ucar.nc2.jni.netcdf.Nc4Iosp.writeData(Nc4Iosp.java:2859)
        at ucar.nc2.jni.netcdf.Nc4Iosp.writeData(Nc4Iosp.java:2809)
        at ucar.nc2.NetcdfFileWriter.write(NetcdfFileWriter.java:958)
        at ucar.nc2.NetcdfFileWriter.write(NetcdfFileWriter.java:942)
        at ucar.nc2.FileWriter2.copyAll(FileWriter2.java:431)
        at ucar.nc2.FileWriter2.copyVarData(FileWriter2.java:384)
        at ucar.nc2.FileWriter2.write(FileWriter2.java:199)
        at ucar.nc2.dataset.NetcdfDataset.main(NetcdfDataset.java:1936)
```

Without the -netcdf4 option the conversion completes but then I have to re-do the conversion with the same ncml (different location) to compress to netcdf4.

**Comment by cofinoa** [comment]
@Gnafu please could you clarify which file are you using as input for the ncml?

For example the files from you are trying to convert have only one data variable and the size in lat and lon dimension differs from the ncml specificatio:

```
netcdf \20180214-JPL_OUROCEAN-L4UHfnd-GLOB-v01-fv01_0-G1SST {
dimensions:
	time = 1 ;
	lon = 36000 ;
	lat = 16000 ;
variables:
	int time(time) ;
		time:units = "seconds since 1981-01-01 00:00:00" ;
		time:long_name = "reference time of sst field" ;
		time:standard_name = "time" ;
		time:axis = "T" ;
		time:calendar = "Gregorian" ;
	float lon(lon) ;
		lon:long_name = "longitude" ;
		lon:standard_name = "longitude" ;
		lon:axis = "X" ;
		lon:units = "degrees_east" ;
	float lat(lat) ;
		lat:long_name = "latitude" ;
		lat:standard_name = "latitude" ;
		lat:axis = "Y" ;
		lat:units = "degrees_north" ;
	short analysed_sst(time, lat, lon) ;
		analysed_sst:_FillValue = -32768s ;
		analysed_sst:add_offset = 273.15f ;
		analysed_sst:scale_factor = 0.01f ;
		analysed_sst:long_name = "analysed sea surface temperature" ;
		analysed_sst:standard_name = "sea_surface_temperature" ;
		analysed_sst:type = "foundation" ;
		analysed_sst:units = "kelvin" ;
		analysed_sst:valid_min = -900s ;
		analysed_sst:valid_max = 4500s ;
	byte mask(time, lat, lon) ;
		mask:long_name = "sea/land/lake/ice field composite mask" ;
		mask:_FillValue = -128b ;
		mask:flag_values = "1b, 2b, 4b, 8b" ;
		mask:flag_meanings = "sea land lake ice" ;
		mask:comment = "b0: 1=grid cell is open sea water\n",
			"b1: 1=land is present in this grid cell\n",
			"b2: 1=lake surface is present in this grid cell\n",
			"b3: 1=sea ice is present in this grid cell\n",
			"b4-b7: reserved for future grid mask data" ;
	short analysis_error(time, lat, lon) ;
		analysis_error:_FillValue = -32768s ;
		analysis_error:add_offset = 273.15f ;
		analysis_error:scale_factor = 0.01f ;
		analysis_error:valid_min = 0s ;
		analysis_error:valid_max = 32767s ;
		analysis_error:long_name = "estimated error standard deviation of analysed_sst" ;
		analysis_error:units = "kelvin" ;

// global attributes:
		:Conventions = "CF-1.0" ;
		:title = "G1SST, 1km blended SST" ;
		:DSD_entry_id = "JPL_OUROCEAN-L4UHfnd-GLOB-G1SST" ;
		:references = "A Blended Global 1-km Sea Surface Temperature Data Set for Research and Applications\n",
			"by Yi Chao, Benyang Tang, Zhijin Li, Peggy Li, Quoc Vu" ;
		:institution = "Jet Propulsion Laboratory, The OurOcean Team" ;
		:contact = "zhijin@jpl.nasa.gov, benyang.tang@jpl.nasa.gov" ;
		:GDS_version_id = "v1.0-rev1.7" ;
		:netcdf_version_id = "3.6.0" ;
		:creation_date = "2018-02-15 UTC" ;
		:product_version = "1.0" ;
		:history = "1km SST blended from 8 satellite observations" ;
		:spatial_resolution = "1 km" ;
		:source_data = "AMSRE,AVHRR,TMI,MODIS,MODIS,GOES,METOP,MTSAT,SEVIRI,AATSR,in-situ" ;
		:comment = "" ;
		:start_date = "2018-02-14 UTC" ;
		:start_time = "00:00:00 UTC" ;
		:stop_date = "2018-02-15 UTC" ;
		:stop_time = "00:00:00 UTC" ;
		:southernmost_latitude = -80.f ;
		:northernmost_latitude = 80.f ;
		:westernmost_longitude = -180.f ;
		:easternmost_longitude = 180.f ;
		:file_quality_index = 0 ;
		:_Format = "classic" ;
}
```

**Comment by cofinoa** [comment]
@Gnafu 
BTW, if you only want to convert variables packed as `short ` type variables (scale and offset) you only need to wrap the original `.nc` with the a `.ncml` like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ncml:netcdf xmlns:ncml="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2" 
  location="20180214-JPL_OUROCEAN-L4UHfnd-GLOB-v01-fv01_0-G1SST.nc"
  enhance="ScaleMissing"
  />
```

where `enhance="ScaleMissing"` will unpack data on variables with scale and offset attributes (see [1]). 

To persist into a new netcdf4 file with deflate and shuffle options use `ucar.nc2.write.Nccopy` class instead `ucar.nc2.dataset.NetcdfDataset` (see [2]): 

```
$java -Xmx2g -classpath ./netcdfAll-4.6.11.jar ucar.nc2.write.Nccopy -f netcdf4_classic -d 9 -sh -i 20180214-JPL_OUROCEAN-L4UHfnd-GLOB-v01-fv01_0-G1SST.ncml -o 20180214-JPL_OUROCEAN-L4UHfnd-GLOB-v01-fv01_0-G1SST.nc4
```
Regards

[1] https://www.unidata.ucar.edu/software/thredds/current/netcdf-java/tutorial/NetcdfDataset.html#enhance
[2] https://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/manPages.html#nccopy

**Comment by Gnafu** [comment]
Hi @cofinoa ,
thank you for your answers and sorry for the long time without a response.

To recap, I have a NetCDF4 with non-homogeneous variables types, and I want to convert all to float. 

The workaround I used until now is to use the ncml (with the float types) from NetCDF4 to NetCDF3 and then use the same ncml to re-convert from NetCDF3 to NetCDF4.
I guess the second step can be done with other tools other than "[...] netcdfAll-4.6.11.jar ucar.nc2.dataset.NetcdfDataset -netcdf4 [...]".

With your suggestion I was able to do a NetCDF4 to NetCDF4 conversion by adding enhance="ScaleMissing" in the ncml, but the resulting file is more than double the size of the 2-step process output file.

![cattura](https://user-images.githubusercontent.com/3932165/43204870-5824d9c6-9022-11e8-87d5-74ff32124c11.PNG)
