### ISSUE TITLE
Nested aggregation failed in TDS 5

### ISSUE THREAD

**Issue by geojs** [Unidata/thredds#1084]
With the latest TDS 5 from :
https://artifacts.unidata.ucar.edu/repository/unidata-snapshots/edu/ucar/tds/5.0.0-SNAPSHOT/tds-5.0.0-20180405.122614-436.war

I have the following error message with OpenDAP (or WMS, HTTPServer) with this URL :
http://localhost:8080/thredds/dodsC/ww3.nc.html

```
Error {
    code = 500;
    message = "barf with read size=1271 in.available=1024";
};
```
The dataset is a union with 2 aggregations by scanning directories.
This configuration works with TDS 4.6.11.

Configuration :
- tomcat-8.5.28
- oracle jdk1.8.0_121
-  catalog.xml
```
  <dataset name="ww3" ID="ww3" urlPath="ww3.nc">
    <metadata inherited="true">
      <serviceName>all</serviceName>
      <dataType>Grid</dataType>
    </metadata>
   <netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
    <aggregation type="union">
       <netcdf>
        <aggregation dimName="time" type="joinExisting">    
         <scan location="/ww3/dp/" suffix="*.nc" subdirs="false"/>
        </aggregation>
       </netcdf> 
       <netcdf>
        <aggregation dimName="time" type="joinExisting">    
         <scan location="/ww3/hs/" suffix="*.nc" subdirs="false"/>
        </aggregation>
       </netcdf> 
      </aggregation>
   </netcdf>   
  </dataset>
```

Logs, threddsServlet.log :
```
2018-04-06T12:12:59.672 +0200 [     39309][      10] INFO  - threddsServlet - Remote host: 127.0.0.1 - Request: "GET /thredds/dodsC/ww3.nc.html HTTP/1.1"
2018-04-06T12:12:59.717 +0200 [     39354][      10] ERROR - thredds.server.opendap.OpendapServlet - request= ReqState:
  serverClassName:    'null'
  dataSet:            'ww3.nc'
  requestSuffix:      'html'
  CE:                 ''
  compressOK:          true
  InitParameters:

java.lang.RuntimeException: barf with read size=1271 in.available=1024
	at thredds.server.catalog.tracker.DatasetExt.readExternal(DatasetExt.java:79) ~[tdcommon-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
	at net.openhft.chronicle.hash.serialization.impl.ExternalizableReader.read(ExternalizableReader.java:49) ~[chronicle-map-3.14.5.jar:3.14.5]
	at net.openhft.chronicle.hash.serialization.impl.ExternalizableReader.read(ExternalizableReader.java:30) ~[chronicle-map-3.14.5.jar:3.14.5]
	at net.openhft.chronicle.hash.serialization.impl.BytesAsSizedReader.read(BytesAsSizedReader.java:42) ~[chronicle-map-3.14.5.jar:3.14.5]
	at net.openhft.chronicle.map.VanillaChronicleMap.searchValue(VanillaChronicleMap.java:635) ~[chronicle-map-3.14.5.jar:3.14.5]
	at net.openhft.chronicle.map.VanillaChronicleMap.tieredValue(VanillaChronicleMap.java:569) ~[chronicle-map-3.14.5.jar:3.14.5]
	at net.openhft.chronicle.map.VanillaChronicleMap.optimizedGet(VanillaChronicleMap.java:521) ~[chronicle-map-3.14.5.jar:3.14.5]
	at net.openhft.chronicle.map.VanillaChronicleMap.get(VanillaChronicleMap.java:470) ~[chronicle-map-3.14.5.jar:3.14.5]
	at thredds.server.catalog.tracker.DatasetTrackerChronicle.findResourceControl(DatasetTrackerChronicle.java:185) ~[tdcommon-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
	at thredds.core.DatasetManager.resourceControlOk(DatasetManager.java:368) ~[classes/:5.0.0-SNAPSHOT]
	at thredds.core.DatasetManager.openNetcdfFile(DatasetManager.java:133) ~[classes/:5.0.0-SNAPSHOT]
	at thredds.core.TdsRequestedDataset.openAsNetcdfFile(TdsRequestedDataset.java:121) ~[classes/:5.0.0-SNAPSHOT]
	at thredds.core.TdsRequestedDataset.getNetcdfFile(TdsRequestedDataset.java:68) ~[classes/:5.0.0-SNAPSHOT]
	at thredds.server.opendap.OpendapServlet.getDataset(OpendapServlet.java:878) ~[classes/:5.0.0-SNAPSHOT]
	at thredds.server.opendap.OpendapServlet.doGetHTML(OpendapServlet.java:552) ~[classes/:5.0.0-SNAPSHOT]
	at thredds.server.opendap.OpendapServlet.doGet(OpendapServlet.java:171) [classes/:5.0.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [servlet-api.jar:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.28]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.28]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.28]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at thredds.servlet.filter.RequestBracketingLogMessageFilter.doFilter(RequestBracketingLogMessageFilter.java:53) [classes/:5.0.0-SNAPSHOT]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at thredds.servlet.filter.RequestCORSFilter.doFilte 
```

The data :
ftp://ftp.ifremer.fr/ifremer/ww3/HINDCAST/NORGAS/2013/dp/ww3.201303_dp.nc
ftp://ftp.ifremer.fr/ifremer/ww3/HINDCAST/NORGAS/2013/dp/ww3.201304_dp.nc
ftp://ftp.ifremer.fr/ifremer/ww3/HINDCAST/NORGAS/2013/dp/ww3.201305_dp.nc

ftp://ftp.ifremer.fr/ifremer/ww3/HINDCAST/NORGAS/2013/hs/ww3.201303_hs.nc
ftp://ftp.ifremer.fr/ifremer/ww3/HINDCAST/NORGAS/2013/hs/ww3.201304_hs.nc
ftp://ftp.ifremer.fr/ifremer/ww3/HINDCAST/NORGAS/2013/hs/ww3.201305_hs.nc

Thanks

**Comment by cofinoa** [comment]
@geojs 

the issue it's not related with the aggregation itself. 

I have tested with toolsui's  version 4.6.11 and 5.0.0-20180405.122224-259 and both work. 

It's a problem with the mechanism been used to persist/cache TDS catalogs in version 5.0 which is one of the major changes with respect to version 4.6

I haven't yet identified exactly the problem, but hope this helps someone else. 

BTW, have you tried again with a "clean" TDS content directory?

**Comment by lesserwhirls** [comment]
Indeed, @cofinoa - this is an issue with the catalog cache. We bumped the version of `ChronicleMap` not too long ago (due to a security related issue), and the older cache files do not seem to be compatible with the new version of that library. @geojs, you should be able to remove the `tds.content.root.path/cache/catalog` directory and restart the TDS to force newer versions of the cache files to be written.

**Comment by geojs** [comment]
I confirm, toolsUI 4.6.11 and 5.0.0-20180405.122224-259 both work.

I remove all the folders from `tds.content.root.path/cache/`, clear the tomcat work and temp directories, restart TDS, the new folders in `tds.content.root.path/cache/` are created.
I still have the same error.

I have the same error with the thredds-docker:
https://github.com/Unidata/thredds-docker
unidata/thredds-docker:5.0-SNAPSHOT
docker-compose up -d thredds-production
(run docker compose, stop docker compose, edit catalog.xml, run docker compose)

Without the  `union `, I dont' have the error, catalog.xml example:
```
  <dataset name="ww3" ID="ww3" urlPath="ww3.nc">
    <metadata inherited="true">
      <serviceName>all</serviceName>
      <dataType>Grid</dataType>
    </metadata>
   <netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
        <aggregation dimName="time" type="joinExisting">    
         <scan location="/ww3/hs/" suffix="*.nc" subdirs="false"/>
        </aggregation>
   </netcdf>   
  </dataset>
```
or
```
  <dataset name="ww3" ID="ww3" urlPath="ww3.nc">
    <metadata inherited="true">
      <serviceName>all</serviceName>
      <dataType>Grid</dataType>
    </metadata>
   <netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
        <aggregation dimName="time" type="joinExisting">    
         <scan location="/ww3/dp/" suffix="*.nc" subdirs="false"/>
        </aggregation>
   </netcdf>   
  </dataset>
```

**Comment by lesserwhirls** [comment]
Hi @geojs - I tried to reproduce this locally, but it seems to work for me. In my case, I did the following:

 * removed everything in `tds.content.root.path`
 * started the TDS (which populated `tds.content.root.path` with the default catalogs)
 * edited `catalog.xml` and added the exact dataset xml snippet in your first message (changed paths to reflect where the data live on my hard drive).

In my case, I am using

* Apache Tomcat `8.5.23`
* Oracle `JDK 1.8.0_131`

**Comment by geojs** [comment]
Thanks you @cofinoa, @lesserwhirls for your tests.

I finally found a workaround, my dataset xml snippet in my first message is not exactly the same (cf file catalog_KO.xml in the [catalog.zip](https://github.com/Unidata/thredds/files/1895493/catalog.zip)), I have some xml comments.
If I remove the comments (cf file catalog_OK.xml in the zip), I don't have the error (test with docker).
If I have a multiple aggregations, I need to write the config with a single line (no line break) :
```
<aggregation type="union"><netcdf><aggregation dimName="time" type="joinExisting"><scan location="/usr/local/tomcat/content/ww3/dp/" suffix="*.nc" subdirs="false"/></aggregation></netcdf><netcdf><aggregation dimName="time" type="joinExisting"><scan location="/usr/local/tomcat/content/ww3/hs/" suffix="*.nc" subdirs="false"/></aggregation></netcdf><netcdf><aggregation dimName="time" type="joinExisting"><scan location="/usr/local/tomcat/content/ww3/fp/" suffix="*.nc" subdirs="false"/></aggregation></netcdf><netcdf><aggregation dimName="time" type="joinExisting"><scan location="/usr/local/tomcat/content/ww3/cur/" suffix="*.nc" subdirs="false"/></aggregation></netcdf><netcdf><aggregation dimName="time" type="joinExisting"><scan location="/usr/local/tomcat/content/ww3/dpt/" suffix="*.nc" subdirs="false"/></aggregation></netcdf></aggregation>
```

**Comment by geojs** [comment]
I pinpoint the origin of the error, the xml (ncml content as a string) return by the cache is truncated, in this class
https://github.com/Unidata/thredds/blob/5.0.0/tdcommon/src/main/java/thredds/server/catalog/tracker/DatasetExt.java#L76
if I replace:
```
in.read(b);
```
with:
```
in.readFully(b);
```
The xml is no more truncated.

There is maybe the same issue with:
https://github.com/Unidata/thredds/blob/5.0.0/tdcommon/src/main/java/thredds/server/catalog/tracker/CatalogExt.java#L82
https://github.com/Unidata/thredds/blob/5.0.0/tdcommon/src/main/java/thredds/server/catalog/tracker/DataRootExt.java#L115
