### ISSUE TITLE
Zeros Returned instead of fill value for times when variable does not exist in record

### ISSUE THREAD

**Issue by SBFRF** [Unidata/thredds#1096]
When I have multiple netCDF files in an aggregation data set with a file(s) that has a missing variable the server will return zeros for the time period in which the variables don't exist.  

When reading the data set the whole variable cannot be read but instead one could read [:-1]. Surprisingly, Thredds (or OpenDAP) replaces the missing values (e.g. when an nc files has in incorrectly named or missing variable) with zero.  So, if the data set has an .nc file that is missing a variable (that is in every other months file), it will return zeros for that month provided the variable is loaded with up to N-1 data points.

eg: for the variable 'waveTpPeak'
``` 
 import netCDF4 as nc
ncfile = nc.Dataset('Blockedhttps://chlthredds.erdc.dren.mil/thredds/dodsC/frf/oceanography/waves/xp125m/xp125m.ncmlBlocked')  # please note this record has been fixed ``
ncfile['waveTpPeak'][:]
Traceback (most recent call last):
   File "/opt/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2882, in run_code
     exec(code_obj, self.user_global_ns, self.user_ns)
   File "<ipython-input-17-1d5593c5c5e7>", line 1, in <module>
     ncfile['waveTpPeak'][:]
   File "netCDF4/_netCDF4.pyx", line 3961, in netCDF4._netCDF4.Variable.__getitem__
   File "netCDF4/_netCDF4.pyx", line 4798, in netCDF4._netCDF4.Variable._get
   File "netCDF4/_netCDF4.pyx", line 1638, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: file not found​
# to work around this (and other issues) use indexing that removes one value.... 
plt.plot(nc.num2date(ncfile['time'][:-1], ncfile['time'].units), ncfile['waveTpPeak'][:-1], '.')
```
![badfillvalue](https://user-images.githubusercontent.com/8375832/40124848-6ffe4de6-58f7-11e8-877a-952a14770774.png)
 
The transition files have been attached to this post to isolate a short time period in which the dataset goes  from not having the variable to having the variable:  the November file (*201711.nc) does not have this variable in it.  December  (*201712.nc) does have this variable (with one record in it) and January (*201801.nc) has a full record (hourly data). 
[FRF-ocean_waves_xp125m_dataset.zip](https://github.com/Unidata/thredds/files/2009727/FRF-ocean_waves_xp125m_dataset.zip)

**Comment by DennisHeimbigner** [comment]
What behavior do you think we should implement for a missing variable?

**Comment by SBFRF** [comment]
Hey Dennis, 
I think in this instance, the fill value (-999 in this case --- if its provided) should be returned instead of Zeros.  Which is (or could be) a viable data value.  If there's no fill value provided in the file or ncml dataset.  I'm not really sure what to say, certainly open to discussion. 

The other thing that would be helpful in this case if the server could handle the query without requiring the data[0:-1] or data[1:end].  I know this is a symptom of other issues so maybe it's a larger issue or a default behavior of the server that allows for the user get around an error.  Maybe this is a separate issue and should be addressed as such.

It seems my responses more address the symptoms than the error or a missing variable, and it seems you're asking how to address the error itself.  To answer that: I'm not sure how to address it because It's a data provider problem (in consistent files across the Dataset) .  I don't know if a warning message from the server could/should be displayed alerting the user they're accessing data outside of the variables in the files or if simply filling them would be good enough, then requiring the data provider to be the stewards of their data.
