### ISSUE TITLE
GribCollection fails in general case of CoordinateTime2D 

### ISSUE THREAD

**Issue by JohnLCaron** [Unidata/thredds#1230]
This issue has been there forever, but the recent change of the default "ignore zero intervals" (was true, now false), has exposed the problem in one or more of our test datasets.

Reproduce by creating an ncx4 from cdmUnitTest/datasets/NDFD-CONUS-5km/.*grib2.

eg put the above expression in ToosUI,  IOSP/Grib2/Grib2Collection, then choose (rightmost icon) "Write Index", you will get:

GribCoverageDataset.open failed
java.lang.IllegalStateException: Time2D with type= MRC
	at ucar.nc2.grib.coverage.GribCoverageDataset.makeTime2DCoordinates(GribCoverageDataset.java:512)
	at ucar.nc2.grib.coverage.GribCoverageDataset.createCoverageCollection(GribCoverageDataset.java:180)
	at ucar.nc2.grib.coverage.GribCoverageDataset.open(GribCoverageDataset.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ucar.nc2.ft2.coverage.CoverageDatasetFactory.openGrib(CoverageDatasetFactory.java:113)
	at ucar.nc2.ft2.coverage.CoverageDatasetFactory.openCoverageDataset(CoverageDatasetFactory.java:61)

For NDFD thredds serving, can put the ""ignore zero intervals" back to true. But the general case should be fixed somehow.

**Comment by JohnLCaron** [comment]
Another example of a collection neighter orthogonal or regular:

cdmUnitTest/gribCollections/rdavm/ds094.2/diurnal_timeseries/.*gbx9

failing here:

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 0
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:75)
	at ucar.coord.CoordinateTime2D.<init>(CoordinateTime2D.java:132)
	at ucar.coord.CoordinateTime2DUnionizer.makeCoordinate(CoordinateTime2DUnionizer.java:108)
	at ucar.coord.CoordinateBuilderImpl.finish(CoordinateBuilderImpl.java:45)
	at ucar.coord.CoordinateSharer.finish(CoordinateSharer.java:161)
	at ucar.nc2.grib.collection.Grib2CollectionBuilder$Grib2Rectilyser.make(Grib2CollectionBuilder.java:285)
	at ucar.nc2.grib.collection.Grib2CollectionBuilder.makeGroups(Grib2CollectionBuilder.java:133)
	at ucar.nc2.grib.collection.GribCollectionBuilder.createMultipleRuntimeCollections(GribCollectionBuilder.java:122)
	at ucar.nc2.grib.collection.GribCollectionBuilder.createIndex(GribCollectionBuilder.java:114)
	at ucar.nc2.grib.collection.GribCdmIndex.updateGribCollection(GribCdmIndex.java:346)
	at ucar.nc2.grib.collection.GribCdmIndex.updateLeafCollection(GribCdmIndex.java:506)
	at ucar.nc2.grib.collection.GribCdmIndex.updateGribCollection(GribCdmIndex.java:323)
	at ucar.nc2.grib.collection.GribCdmIndex.openGribCollection(GribCdmIndex.java:698)

Not sure why this test stop working, it looks like it should have been failing all along.
