### ISSUE TITLE
NetcdfSubset err=Could not open as Coverage point/grid service not working

### ISSUE THREAD

**Issue by Akshay-Hegde** [Unidata/thredds#1376]
version: unidata/thredds-docker:5.0

Services working : Opendap, DAP4,http,ISO,NCML.CDMremote.

**Service not working : NetcdfSubset : Either grid or point throwing error**

Sample file for testing: [testfile.zip](https://github.com/Unidata/thredds/files/7357931/testfile.zip)

```
$  ferret
 	NOAA/PMEL TMAP
 	PyFerret v7.63 (optimized)
 	Linux 4.15.0-1096-azure - 10/13/20
 	16-Oct-21 22:35     

yes? use testfile.nc
yes? sh d
     currently SET data sets:
    1> ./testfile.nc  (default)
 name     title                             I         J         K         L
 U        U_1205                           1:1       1:1       1:10      1:20
 V        V_1206                           1:1       1:1       1:10      1:20
 
yes? sh g u
    GRID GNL1
 name       axis              # pts   start                end                 subset
 LON       LONGITUDE            1 r   72.744E(72.744)      72.744E(72.744)     full
 LAT       LATITUDE             1 r   15.166N              15.166N             full
 DEPTH1_10 DEPTH (m)           10 r-  -101.42              -65.421             full
 TIME      TIME                20 r   03-OCT-2017 16:00    04-OCT-2017 11:00   full


$ ncdump -h testfile.nc 
netcdf testfile {
dimensions:
	LON = 1 ;
	LAT = 1 ;
	DEPTH1_10 = 10 ;
	TIME = UNLIMITED ; // (20 currently)
variables:
	float LON(LON) ;
		LON:long_name = "Longitude" ;
		LON:units = "degrees_east" ;
		LON:point_spacing = "even" ;
		LON:axis = "X" ;
		LON:standard_name = "longitude" ;
	float LAT(LAT) ;
		LAT:long_name = "Latitude" ;
		LAT:units = "degrees_north" ;
		LAT:point_spacing = "even" ;
		LAT:axis = "Y" ;
		LAT:standard_name = "latitude" ;
	float DEPTH1_10(DEPTH1_10) ;
		DEPTH1_10:long_name = "Depth (m)" ;
		DEPTH1_10:units = "meters" ;
		DEPTH1_10:positive = "down" ;
		DEPTH1_10:point_spacing = "even" ;
		DEPTH1_10:axis = "Z" ;
		DEPTH1_10:standard_name = "depth" ;
	float TIME(TIME) ;
		TIME:long_name = "Time" ;
		TIME:units = "hours since 2017-10-03 16:00:00" ;
		TIME:time_origin = "03-OCT-2017 16:00:00" ;
		TIME:axis = "T" ;
		TIME:standard_name = "time" ;
	double U(TIME, DEPTH1_10, LAT, LON) ;
		U:missing_value = -1.e+34 ;
		U:_FillValue = -1.e+34 ;
		U:long_name = "U_1205" ;
		U:history = "From test" ;
	double V(TIME, DEPTH1_10, LAT, LON) ;
		V:missing_value = -1.e+34 ;
		V:_FillValue = -1.e+34 ;
		V:long_name = "V_1206" ;
		V:history = "From test" ;

// global attributes:
		:history = "PyFerret V7.63 (optimized) 16-Oct-21" ;
		:Conventions = "CF-1.6" ;
}

```

Error Log

```
2021-10-16T17:07:39.658 +0000 [   1937647][     245] INFO  - threddsServlet - Request Completed - 302 - -1 - 2
2021-10-16T17:07:41.631 +0000 [   1939620][     246] INFO  - threddsServlet - Remote host: 172.31.0.1 - Request: "GET /thredds/ncss/grid/test/data/testfile.nc/dataset.html HTTP/1.1"
2021-10-16T17:07:41.708 +0000 [   1939697][     246] WARN  - thredds.server.TdsErrorHandling - TDS Error
java.io.FileNotFoundException: Not a Grid Dataset test/data/testfile.nc err=Could not open as Coverage: /test/testfile.nc
	at thredds.core.DatasetManager.openCoverageDataset(DatasetManager.java:416) ~[classes/:5.0]
	at thredds.core.TdsRequestedDataset.openAsCoverageDataset(TdsRequestedDataset.java:138) ~[classes/:5.0]
	at thredds.core.TdsRequestedDataset.getCoverageCollection(TdsRequestedDataset.java:72) ~[classes/:5.0]
	at thredds.server.ncss.controller.NcssGridController.getDatasetDescriptionHtml(NcssGridController.java:232) ~[classes/:5.0]
	at thredds.server.ncss.controller.NcssGridController.getGridDatasetDescriptionHtml(NcssGridController.java:219) ~[classes/:5.0]
	at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeA

```

**Comment by Akshay-Hegde** [comment]
Issue seems similar to https://github.com/Unidata/thredds/issues/1054

Is there any solution ?
