### ISSUE TITLE
Bugs/typos/documentation in 4.6.3

### ISSUE THREAD

**Issue by rjdave** [Unidata/thredds#187]
Hello,

I upgraded from TDS 4.3 to 4.6 on September 8th and have noticed several peculiarities involving FMRC datasets. I am running java 1.8.0_60 and tomcat 8.0.24 and started my configuration from the stock tomcat files.

The catalog xml file I'm referring to in issues 3-6 stated below can be found [here] (https://gist.github.com/297df1e45edc08c22a1e.git). I have since removed the **rescan** attributes. 

The data in question are hourly files (each file contains one record resulting in 24 files a day) with recently created files occasionally being modified. The data is CODAR totals that are built as soon as enough radial data is acquired to compute a total. However, if more radials are acquired between cron jobs the totals for that hour (already in the FMRC) are recomputed and the file is replaced. The unlimited dimension and metadata do not change. This worked fine 4.3 using a TDS trigger to get the latest data into the FMRC but I ran into some issues after upgrading to 4.6, most of which I have solved and/or found a workaround for.

4.6 FMRC issues I encountered:
--------------------------------------------------------------------------------------------------

1. When looking through the catalogInit.log I noticed that there are some XML parse errors when you use the "offsetsGreaterEqual" config option. For each such dataset the following entries appear in the log:<br><br>*** XML parser error (94:61)= cvc-complex-type.3.2.2: Attribute 'offsetsGreaterEqual' is not allowed to appear in element 'dataset'.<br>*** XML parser error (95:23)= cvc-complex-type.2.1: Element 'fmrcConfig' must have no character or element information item [children], because the type's content type is empty.<br><br>However, the offset appears to work and the offset appears in the TDM:<br><br>fmrcConfig= FmrcConfig: regularize=false datasetTypes=[TwoD, Files, Runs, ConstantOffsets]best = (Best, 25.000000)<br><br>The block of catalog XML that triggers this is:<br><br>&lt;fmrcConfig regularize="false" datasetTypes="TwoD Runs ConstantOffsets Files"&gt;<br>&nbsp;&nbsp;&nbsp;&lt;dataset name="Best" offsetsGreaterEqual="25" /&gt;<br>    &lt;/fmrcConfig&gt;

2. The above block makes the "Best Time Series" entry you normally see (when you don't use offsetsGreaterEqual) render as just "Best":<br><br>http://tds.marine.rutgers.edu/thredds/catalog/roms/espresso/2013_da/avg/catalog.html<br><br>Notice that the second entry is "Best" while in normal (non-offsetsGreaterEqual) FMRC datasets on the same server the link is titled "Best Time Series".

3. The format of the trigger URL appears to have changed and seems broken in several ways. The name of the trigger has changed and it seemed in order to get a non-error response **&trigger=nocheck** had to be appended to the URL when executed with wget or a browser. I got this idea from the documentation that mentions that the TDM adds that to the standard trigger URL. That said, even though I got a **TRIGGER Sent** response the dataset was not updated, possibly because of "nocheck".<br><br>I also tried clicking the "Send trigger to" link when logged in to the TDM and it returns "TRIGGER Sent" but the dataset does not update (**nocheck** again). What are the other options for "&trigger=" and why doesn't the old trigger (that forced a rescan) work anymore?<br><br>**SOLVED:** I noticed that in the documentation all of the &lt;update&gt; lines had startup="test" so on a whim I tried using **&trigger=test** and that did indeed trigger an update of the datasets. Can you confirm that this correct and possibly update the documentation as well? The dataset in question is added to hourly.

4. While trying to figure out the trigger problem above, as an experiment, I deleted the cache for my dataset through the TDM then sent (successfully) the trigger from the TDM and the following error (truncated) appears in fmrc.log:<br><br>[2015-09-09T08:53:45.151-0400] ERROR ucar.nc2.ft.fmrc.Fmrc: Maracoos_5MHz_6km_Totals-FMRC: makeFmrcInv failed java.lang.RuntimeException: java.lang.IllegalStateException: Can't call Database.get: Database was closed.<br><br>I tried this on another dataset with the same result. It's also a little curious that the trigger link in the TDM shows the name from the "&lt;featureCollection&gt;" name but the actual trigger is using the name from "&lt;collection&gt;". I'm pretty sure 4.3 used the name from &lt;featureCollection&gt; for both.<br><br>I tried sending a trigger using **&trigger=test** but while it doesn't produce the error, it does not appear to rebuild the cache. The only way I have found to get the deleted cache to rebuild is by restarting the server.

5. Another thing I discovered while working on  # 3 is that<br><br>**&lt;update startup="nocheck" rescan="0 35 * * * ? *" trigger="allow" /&gt;**<br><br>does not update a dataset. Sometimes I get the following entry in fmrc.log but the dataset does not update:<br><br>[2015-09-09T11:35:19.245-0400] WARN  ucar.nc2.ft.fmrc.GridDatasetInv:  xmlFile in cache only has nbytes =246; will reread<br><br>**SOLVED:** Changing the line to<br><br>**&lt;update startup="test" rescan="0 35 * * * ? *" trigger="allow" /&gt;**<br><br>(a hint from the documentation) seems to work. Therefore, is it safe to assume that when you use the **rescan** attribute it uses whatever method you have set the startup attribute to? This seems counter intuitive as you'd expect a **rescan** to scan your dataset and look for new data and not just check if the index exist since it would obviously exist after startup if you use the **nocheck** option.

6. I have **&lt;update startup="nocheck" trigger="allow"/&gt;** on some datasets but when I start up the server I get several lines like:<br><br>[2015-09-09T09:08:33.034-0400] WARN  ucar.nc2.ft.fmrc.GridDatasetInv:  xmlFile in cache only has nbytes =248; will reread
[2015-09-09T09:08:33.468-0400] INFO  ucar.nc2.ft.fmrc.GridDatasetInv:  cache out of date Wed Sep 09 07:46:03 EDT 2015 &lt; Wed Sep 09 08:48:22 EDT 2015 for RU_25MHz_2015_09_09_1000.totals.nc<br><br>perhaps I misunderstand what **startup="nocheck"** means. If this is a dataset that already had an index shouldn't **nocheck** do nothing even if a file has since been modified?

Thanks,
Dave

**Comment by JohnLCaron** [comment]
Hi Dave:

Sorry, I didnt get 

https://gist.github.com/rjdave/297df1e45edc08c22a1e

before it disappeared. Can you repost?

John

**Comment by JohnLCaron** [comment]
> The format of the trigger URL appears to have changed and seems broken in several ways. The name of the trigger has changed and it seemed in order to get a non-error response &trigger=nocheck

yes, you are right. The trigger URL changed and the docs were not updated. The trigger URL must have a "&trigger=type" parameter. For FMRC the type should be *test* or *nocheck*.

we will get the docs updated, sorry for missing that.

**Comment by JohnLCaron** [comment]
Can you send the entire stack trace for this message:

2015-09-09T08:53:45.151-0400] ERROR ucar.nc2.ft.fmrc.Fmrc: Maracoos_5MHz_6km_Totals-FMRC: makeFmrcInv failed java.lang.RuntimeException: java.lang.IllegalStateException: Can't call Database.get: Database was closed.

thanks

**Comment by JohnLCaron** [comment]
Not sure what this means:

"I deleted the cache for my dataset through the TDM " ?

BTW, TDM does not work with FMRC.

**Comment by JohnLCaron** [comment]
> the trigger link in the TDM shows the name from the "<featureCollection>" name but the actual trigger is using the name from "<collection>". I'm pretty sure 4.3 used the name from <featureCollection> for both.

yes, in 4.6 the collection element has a name separate from featureCollection name, so featureCollection can be "human readable" and change if needed. collection name should have no spaces and not change.

**Comment by JohnLCaron** [comment]
> Therefore, is it safe to assume that when you use the rescan attribute it uses whatever method you have set the startup attribute to? This seems counter intuitive as you'd expect a rescan to scan your dataset and look for new data and not just check if the index exists since it would obviously exist after startup if you use the nocheck option.

correct, and i agree its not well named. rescan uses the updateType from startup. perhaps we should separate them.

**Comment by JohnLCaron** [comment]
> [2015-09-09T09:08:33.034-0400] WARN ucar.nc2.ft.fmrc.GridDatasetInv: xmlFile in cache only has nbytes =248; will reread

means that its likely that there was an error in creating the XML "cache file", so it will recreate it.

**Comment by rjdave** [comment]
The catalog file still seems to be visible but try this "permalink":

https://gist.github.com/rjdave/297df1e45edc08c22a1e#file-cat_totals-xml

**Comment by rjdave** [comment]
>Can you send the entire stack trace for this message:
>
>[2015-09-09T08:53:45.151-0400] ERROR ucar.nc2.ft.fmrc.Fmrc: Maracoos_5MHz_6km_Totals-FMRC: makeFmrcInv failed java.lang.RuntimeException: java.lang.IllegalStateException: Can't call Database.get: Database was closed.
>
>thanks

[2015-09-09T08:53:45.151-0400] ERROR ucar.nc2.ft.fmrc.Fmrc: makeFmrcInv
java.lang.IllegalStateException: Can't call Database.get: Database was closed.
   at com.sleepycat.je.Database.checkOpen(Database.java:1751) ~[je-4.0.92.jar:?]
   at com.sleepycat.je.Database.get(Database.java:878) ~[je-4.0.92.jar:?]
   at thredds.inventory.bdb.MetadataManager.getBytes(MetadataManager.java:300) ~[clcommon-4.6.3.jar:4.6.3]
   at thredds.inventory.CollectionManagerAbstract.getMetadata(CollectionManagerAbstract.java:142) ~[cdm-4.6.3.jar:?]
   at ucar.nc2.ft.fmrc.GridDatasetInv.open(GridDatasetInv.java:90) ~[cdm-4.6.3.jar:4.6.3]
   at ucar.nc2.ft.fmrc.Fmrc.makeFmrcInv(Fmrc.java:280) [cdm-4.6.3.jar:4.6.3]
   at ucar.nc2.ft.fmrc.Fmrc.update(Fmrc.java:235) [cdm-4.6.3.jar:4.6.3]
   at thredds.catalog.InvDatasetFcFmrc.updateCollection(InvDatasetFcFmrc.java:107) [tdcommon-4.6.3.jar:4.6.3]
   at thredds.catalog.InvDatasetFeatureCollection.update(InvDatasetFeatureCollection.java:340) [tdcommon-4.6.3.jar:4.6.3]
   at thredds.catalog.InvDatasetFcFmrc.update(InvDatasetFcFmrc.java:95) [tdcommon-4.6.3.jar:4.6.3]
   at thredds.catalog.InvDatasetFeatureCollection.sendEvent(InvDatasetFeatureCollection.java:228) [tdcommon-4.6.3.jar:4.6.3]
   at thredds.inventory.CollectionUpdater$UpdateCollectionJob.execute(CollectionUpdater.java:242) [cdm-4.6.3.jar:?]
   at org.quartz.core.JobRunShell.run(JobRunShell.java:207) [quartz-2.2.0.jar:?]
   at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:560) [quartz-2.2.0.jar:?]
[2015-09-09T08:53:45.151-0400] ERROR ucar.nc2.ft.fmrc.Fmrc: Maracoos_5MHz_6km_Totals-FMRC: makeFmrcInv failed
java.lang.RuntimeException: java.lang.IllegalStateException: Can't call Database.get: Database was closed.
   at ucar.nc2.ft.fmrc.Fmrc.makeFmrcInv(Fmrc.java:312) ~[cdm-4.6.3.jar:4.6.3]
   at ucar.nc2.ft.fmrc.Fmrc.update(Fmrc.java:235) [cdm-4.6.3.jar:4.6.3]
   at thredds.catalog.InvDatasetFcFmrc.updateCollection(InvDatasetFcFmrc.java:107) [tdcommon-4.6.3.jar:4.6.3]
   at thredds.catalog.InvDatasetFeatureCollection.update(InvDatasetFeatureCollection.java:340) [tdcommon-4.6.3.jar:4.6.3]
   at thredds.catalog.InvDatasetFcFmrc.update(InvDatasetFcFmrc.java:95) [tdcommon-4.6.3.jar:4.6.3]
   at thredds.catalog.InvDatasetFeatureCollection.sendEvent(InvDatasetFeatureCollection.java:228) [tdcommon-4.6.3.jar:4.6.3]
   at thredds.inventory.CollectionUpdater$UpdateCollectionJob.execute(CollectionUpdater.java:242) [cdm-4.6.3.jar:?]
   at org.quartz.core.JobRunShell.run(JobRunShell.java:207) [quartz-2.2.0.jar:?]
   at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:560) [quartz-2.2.0.jar:?]
Caused by: java.lang.IllegalStateException: Can't call Database.get: Database was closed.
   at com.sleepycat.je.Database.checkOpen(Database.java:1751) ~[je-4.0.92.jar:?]
   at com.sleepycat.je.Database.get(Database.java:878) ~[je-4.0.92.jar:?]
   at thredds.inventory.bdb.MetadataManager.getBytes(MetadataManager.java:300) ~[clcommon-4.6.3.jar:4.6.3]
   at thredds.inventory.CollectionManagerAbstract.getMetadata(CollectionManagerAbstract.java:142) ~[cdm-4.6.3.jar:?]
   at ucar.nc2.ft.fmrc.GridDatasetInv.open(GridDatasetInv.java:90) ~[cdm-4.6.3.jar:4.6.3]
   at ucar.nc2.ft.fmrc.Fmrc.makeFmrcInv(Fmrc.java:280) ~[cdm-4.6.3.jar:4.6.3]
   ... 8 more

**Comment by rjdave** [comment]
>Not sure what this means:
>
>"I deleted the cache for my dataset through the TDM " ?
>
>BTW, TDM does not work with FMRC.

TDM is probably the wrong thing to say here. I logged into the **thredds/admin/debug** interface, clicked **Show FMRC Cache** => **5MHz_6km_realtime_codar_fmrc** (displaying the full path to every file in the FMRC cache) and clicked the the "Delete" link at the top.

Then I went back to  **thredds/admin/debug** and clicked **Show Collections** => **Maracoos_5MHz_6km_Totals-FMRC** => **Send trigger to Maracoos_5MHz_6km_Totals-FMRC**. This shows the **TRIGGER SENT** confirmation. I also changed the URL to say **trigger=test** and resubmitted. That also showed **TRIGGER SENT** and while it did not cause the error in the fmrc.log, it did not seem to rebuild the cache either.

I cannot remember if I attempted to access the dataset after sending the triggers but I seem to remember it displaying an error.

Dave

**Comment by JohnLCaron** [comment]
Been figuring out a few more pieces of this:

> *** XML parser error (94:61)= cvc-complex-type.3.2.2: Attribute 'offsetsGreaterEqual' is not allowed to appear in element 'dataset'.
> *** XML parser error (95:23)= cvc-complex-type.2.1: Element 'fmrcConfig' must have no character or element information item [children], because the type's content type is empty.

this feature never got added to the schema. I will add it to 4.6 and 5.0, and in the meanwhile the errors can be ignored.

In 5.0, this syntax will change from:

<fmrcConfig regularize="false" datasetTypes="TwoD Runs ConstantOffsets Files">
   <dataset name="Best" offsetsGreaterEqual="25" />
</fmrcConfig>

to

<fmrcConfig regularize="false" datasetTypes="TwoD Runs ConstantOffsets Files">
   <bestDataset name="Best" offsetsGreaterEqual="25" />
</fmrcConfig>

to clarify things.

**Comment by JohnLCaron** [comment]
(guess i should have previewed that)

Been figuring out a few more pieces of this:

*** XML parser error (94:61)= cvc-complex-type.3.2.2: Attribute 'offsetsGreaterEqual' is not allowed to appear in element 'dataset'.
*** XML parser error (95:23)= cvc-complex-type.2.1: Element 'fmrcConfig' must have no character or element information item [children], because the type's content type is empty.
this feature never got added to the schema. I will add it to 4.6 and 5.0, and in the meanwhile the errors can be ignored.

In 5.0, this syntax will change from:

```xml
 <fmrcConfig regularize="false" datasetTypes="TwoD Runs ConstantOffsets Files">
   <dataset name="Best" offsetsGreaterEqual="25" />
 </fmrcConfig>
```

to

```xml
 <fmrcConfig regularize="false" datasetTypes="TwoD Runs ConstantOffsets Files">
   <bestDataset name="Best" offsetsGreaterEqual="25" />
 </fmrcConfig>
```


to clarify things.

**Comment by JohnLCaron** [comment]
```xml
 <fmrcConfig regularize="false" datasetTypes="TwoD Runs ConstantOffsets Files">
   <dataset name="Best" offsetsGreaterEqual="25" />
 </fmrcConfig>
```

> Notice that the second entry is "Best" while in normal (non-offsetsGreaterEqual) FMRC datasets on the same server the link is titled "Best Time Series".

Standard "Best Dataset" is done by adding "Best" to datasetTypes. With \<dataset\> it just uses whatever name you use, so you could change to 

```xml
   <dataset name="Best Time Series" offsetsGreaterEqual="25" />
```

if you want.

**Comment by JohnLCaron** [comment]
> I deleted the cache for my dataset through the (admin interface) 
then sent (successfully) the trigger from the TDM and the following error (truncated) appears in fmrc.log:

> [2015-09-09T08:53:45.151-0400] ERROR ucar.nc2.ft.fmrc.Fmrc: Maracoos_5MHz_6km_Totals-FMRC: makeFmrcInv failed java.lang.RuntimeException: java.lang.IllegalStateException: 
Can't call Database.get: Database was closed.

"Deleting the cache" means deleting the "database" for that collection. After that, the FMRC should be told to reread the collection, so that the cache will be recreated. I will look into adding that. For now, the correct thing is to restart the TDS.

**Comment by dopplershift** [comment]
@JohnLCaron FYI, you should be able to go back and edit a comment (click on the pencil icon) if you need to correct something.

**Comment by JohnLCaron** [comment]
Hi Dave:

So despite these glitches, does it work as in 4.3, with a trigger correctly recreating the collection?

Can I get a sample filt to have a look at?

John

**Comment by rjdave** [comment]
>Standard "Best Dataset" is done by adding "Best" to datasetTypes. With <dataset> it just uses whatever name you use, so you could change to
>```xml
>   <dataset name="Best Time Series" offsetsGreaterEqual="25" />`
>```
>if you want.

That was the first thing I tried. While it all looks good, when you click the final link for OPENDAP under the **Access:** heading you get a 404 error:

```
Error {
    code = 404;
    message = "roms/espresso/2013_da/avg/ESPRESSO_Real-Time_v2_Averages_Best_Time_Series";
};
```

**Comment by rjdave** [comment]
>Hi Dave:
>
>So despite these glitches, does it work as in 4.3, with a trigger correctly recreating the collection?

I'm not sure what you were referring to here so I will give you two answers:

1. In 4.3 when I delete the cache through https://.../thredds/admin/debug then send the trigger through the same interface (or with wget and the old-style trigger URL) the collection is recreated and no errors occur.

2. If you meant does a properly formed trigger in 4.6 result in a rescan of the data, picking up new and changed files as it did in 4.3 (with the old trigger syntax) then yes.

>Can I get a sample filt to have a look at?

Can you clarify what you mean by this? I'm not understanding "sample filt".

**Comment by JohnLCaron** [comment]
1) ok, let me test that name thing. might be you cant use spaces.

2) ok. we are updating documentation about the change in trigger URL

3) sorry, "sample file". my fingers operate indpependently of my brain :^)

**Comment by rjdave** [comment]
I put a small collection of CODAR files in a folder and put them in the catalog as a datasetScan with both opendap and http services enabled. Please let me know if you need more files than this.

http://tds.marine.rutgers.edu/thredds/catalog/cool/codar/totals/unidata/catalog.html

**Comment by cwardgar** [comment]
Does the discussion in this thread and John's PR (#209) fully address the problem? If so, I can close this issue.

**Comment by rsignell-usgs** [comment]
@cwardgar I think if the latest schema is 
then we still have a problem. 

[This TDS 4.6 FMRC catalog](https://gist.github.com/rsignell-usgs/de57456115d795b831b18c3e915d2a5d) from @rjdave is failing validation in Oxygen when associated with 
http://www.unidata.ucar.edu/schemas/thredds/InvCatalog.1.0.7.xsd

giving this error:
```
E [Xerces] cvc-complex-type.2.1: Element 'fmrcConfig' must have no character or element information item [children], because the type's content type is empty.
```
despite this catalog containing the exact form of `fmrcConfig` given in the documentation here: 
https://www.unidata.ucar.edu/software/thredds/v4.6/tds/reference/collections/FmrcCollection.html

**Comment by cwardgar** [comment]
Yep, validation issue still exists. We'll need to update the schema. Probably the documentation as well.
