### ISSUE TITLE
Refactor TestReadAndCountDods

### ISSUE THREAD

**Issue by cwardgar** [Unidata/thredds#193]
`TestReadAndCountDods` opens remote datasets on thredds-test and asserts that they contain an expected number of grids, coordinate systems, etc.

The problem is obvious: thredds-test is a dynamic resource, and `TestReadAndCountDods` frequently fails when thredds-test is changed (usually during an update). Trying to assert anything about a dynamic resource is a terrible testing strategy. This test needs to change, possibly to use mock objects.

Indeed, there are surely other tests that are trying to work with a moving target, and they should be rewritten as well. However, `TestReadAndCountDods` is the one I see failing most often.

**Comment by DennisHeimbigner** [comment]
If the underlying test files are not too large, then one solution:
1. add those files (or a subset) to the tdsConfig branch for remotetest.
2. modify TestAndCountDods to point to those files

**Comment by cwardgar** [comment]
Got another periodic failure:

```
ucar.unidata.geoloc.TestProjections > testUTM FAILED
    java.lang.AssertionError: ucar.unidata.geoloc.projection.UtmProjection lon failed start= 9.544S 4.009E-4E end = 9.544S 4.097E-4E diff = 0.021809543532190712
        at ucar.unidata.geoloc.TestProjections.testProjectionUTM(TestProjections.java:430)
        at ucar.unidata.geoloc.TestProjections.testUTM(TestProjections.java:376)
```

**Comment by cwardgar** [comment]
And another:

```
ucar.nc2.dt.grid.TestTime2D > testTime2D FAILED
    java.io.IOException: java.io.IOException: opendap.dap.DAP2Exception: opendap.dap.DAP2Exception: Method failed:HTTP/1.1 503 Service Temporarily Unavailable on URL= http://thredds-dev.unidata.ucar.edu/thredds/dodsC/grib/NCEP/GFS/Pacific_40km/TwoD.dds
        at ucar.nc2.dataset.NetcdfDataset.openDodsByReflection(NetcdfDataset.java:1034)
        at ucar.nc2.dataset.NetcdfDataset.acquireDODS(NetcdfDataset.java:980)
        at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:711)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:427)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:410)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:395)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:382)
        at ucar.nc2.dt.grid.TestTime2D.testTime2D(TestTime2D.java:52)

        Caused by:
        java.io.IOException: opendap.dap.DAP2Exception: opendap.dap.DAP2Exception: Method failed:HTTP/1.1 503 Service Temporarily Unavailable on URL= http://thredds-dev.unidata.ucar.edu/thredds/dodsC/grib/NCEP/GFS/Pacific_40km/TwoD.dds
            at ucar.nc2.dods.DODSNetcdfFile.<init>(DODSNetcdfFile.java:284)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
            at ucar.nc2.dataset.NetcdfDataset.openDodsByReflection(NetcdfDataset.java:1030)
            ... 7 more

            Caused by:
            opendap.dap.DAP2Exception: opendap.dap.DAP2Exception: Method failed:HTTP/1.1 503 Service Temporarily Unavailable on URL= http://thredds-dev.unidata.ucar.edu/thredds/dodsC/grib/NCEP/GFS/Pacific_40km/TwoD.dds
                at opendap.dap.DConnect2.openConnection(DConnect2.java:328)
                at opendap.dap.DConnect2.getDDS(DConnect2.java:585)
                at opendap.dap.DConnect2.getDDS(DConnect2.java:556)
                at ucar.nc2.dods.DODSNetcdfFile.<init>(DODSNetcdfFile.java:241)
                ... 12 more

                Caused by:
                opendap.dap.DAP2Exception: Method failed:HTTP/1.1 503 Service Temporarily Unavailable on URL= http://thredds-dev.unidata.ucar.edu/thredds/dodsC/grib/NCEP/GFS/Pacific_40km/TwoD.dds
                    at opendap.dap.DConnect2.openConnection(DConnect2.java:290)
                    ... 15 more
```

**Comment by dopplershift** [comment]
On `TestTime2D`, why isn't the `Assume` functionality catching the 503 on thredds-dev? Do we have another junit3 + 4 abomination?

**Comment by cwardgar** [comment]
Hard to say. The `Assume` is pinging `http://thredds-test.unidata.ucar.edu/thredds/` instead of that specific OPenNDAP URL, which might make a difference.

**Comment by cwardgar** [comment]
A lot of these have been silenced on Travis due to #236. However, they're all still running (and often failing) on Jenkins.

**Comment by cwardgar** [comment]
`thredds.server.ncss.controller.grid.GridAsPointDataTest` is another one: it's choosing its parameters from a list of possible values at random. Would be best to print out the failing requests, but the Spring MockMvc machinery makes that tricky.
