### ISSUE TITLE
Getting 5.0.0 green on Travis

### ISSUE THREAD

**Issue by cwardgar** [Unidata/thredds#214]
I thought I could fix all remaining test failures in #211, but I was wrong. In [our latest Travis build result](https://travis-ci.org/Unidata/thredds/builds/82515716), we now have a problem in dap4:
````
dap4.test.TestConstraints > testConstraints STANDARD_ERROR
    java.lang.IllegalArgumentException: setCachedData type=class java.lang.Byte incompatible with variable type=ubyte
    	at ucar.nc2.Variable.setCachedData(Variable.java:1569)
    	at ucar.nc2.Variable.setCachedData(Variable.java:1554)
    	at ucar.nc2.Variable._read(Variable.java:807)
    	at ucar.nc2.Variable.read(Variable.java:681)
    	at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:523)
    	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:507)
    	at ucar.nc2.Variable.read(Variable.java:681)
    	at ucar.nc2.NCdumpW.print(NCdumpW.java:340)
    	at ucar.nc2.NCdumpW.print(NCdumpW.java:242)
    	at dap4.test.TestConstraints.ncdumpdata(TestConstraints.java:248)
    	at dap4.test.TestConstraints.doOneTest(TestConstraints.java:188)
    	at dap4.test.TestConstraints.testConstraints(TestConstraints.java:162)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at junit.framework.TestCase.runTest(TestCase.java:176)
    	at junit.framework.TestCase.runBare(TestCase.java:141)
    	at junit.framework.TestResult$1.protect(TestResult.java:122)
    	at junit.framework.TestResult.runProtected(TestResult.java:142)
    	at junit.framework.TestResult.run(TestResult.java:125)
    	at junit.framework.TestCase.run(TestCase.java:129)
    	at junit.framework.TestSuite.runTest(TestSuite.java:252)
    	at junit.framework.TestSuite.run(TestSuite.java:247)
    	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    NcdumpW failed
````
Clearly, it relates to the unsigned types that were recently added.

@DennisHeimbigner Do you have any ideas? I took a shot at fixing this myself (03a90fe58ee5964f206ad74d8e3ba852586069ef) but ran into a wall, as described in the commit's message.

**Comment by cwardgar** [comment]
[5.0.0 is green as of now](https://travis-ci.org/Unidata/thredds/builds/101373312), so I guess I can close this issue.

The particular test that I mentioned above is no longer running on Travis due to a `NeedsExternalResource` annotation. It may still need to be fixed, but it's impossible to tell until we get thredds-test back up.

**Comment by cwardgar** [comment]
This one is back, as expected. It just wasn't showing up in Jenkins test reports because it's actually been *causing the build to fail* for several weeks. I'm going to submit a PR that fixes the build failure, but this test remains broken.

**Comment by cwardgar** [comment]
Here's the failure on Jenkins: https://jenkins-aws.unidata.ucar.edu/job/thredds5.0/174/testReport/dap4.test/TestConstraints/testConstraints/

**Comment by lesserwhirls** [comment]
@DennisHeimbigner - does your new work on dap4 fix this one?

**Comment by DennisHeimbigner** [comment]
yes.
