### ISSUE TITLE
Projection test failure

### ISSUE THREAD

**Issue by dopplershift** [Unidata/thredds#242]
`TestProjections` caused an unexpected failure upon merging a previously good PR:

```
ucar.unidata.geoloc.TestProjections > testTM FAILED
    java.lang.AssertionError: ucar.unidata.geoloc.projection.TransverseMercator failed start= .01664N 165.0E end = 39.99N 105.0W diff = 2401.7859238345345
        at ucar.unidata.geoloc.TestProjections.testProjection(TestProjections.java:91)
        at ucar.unidata.geoloc.TestProjections.testTM(TestProjections.java:243)
```

**Comment by JohnLCaron** [comment]
Cant see what value of the parameters cause the failure. will change that.

**Comment by cwardgar** [comment]
This test is periodically failing for the same reason as [its brother](https://github.com/Unidata/thredds/issues/193#issuecomment-141217240): the input is random (also called a [monkey test](http://www.tutorialspoint.com/software_testing_dictionary/monkey_testing.htm)). I think we should move away from monkey tests because they don't reliably pass or fail, but it would certainly be useful to record the failing input and use it in a static test.

**Comment by dopplershift** [comment]
Another:
```
ucar.unidata.geoloc.TestProjections > testTM FAILED
    java.lang.AssertionError: .072111263S 165.00490E expected:<-0.07211126381547306> but was:<39.99999999999999>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:553)
        at ucar.unidata.geoloc.TestProjections.testProjection(TestProjections.java:83)
        at ucar.unidata.geoloc.TestProjections.testTM(TestProjections.java:231)
```

**Comment by dopplershift** [comment]
Looks to be fixed now.
