### ISSUE TITLE
NetcdfFile.openInMemory() fails in 4.3

### ISSUE THREAD

**Issue by kenahoo** [Unidata/thredds#32]
In NetCDF 4.2, I do the following, which works:

```java
FileInputStream is = new FileInputStream(testPath);
DataInputStream dis = new DataInputStream(is);
byte[] buf = new byte[(int) is.getChannel().size()];
dis.readFully(buf);

ncf = NetcdfFile.openInMemory("in-mem file", buf);
```

However, in NetCDF 4.3.19, this now fails because opening the "file" seems to force the creation of an index on disk, and something goes haywire in this process.  See stack trace below.

Any way to disable index creation, or a better strategy to use?

My use case is one where I'm handed the bytes of a Grib file, which doesn't necessarily exist anywhere on disk.

Thanks.

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -37
	at java.lang.String.substring(String.java:1937)
	at java.lang.String.substring(String.java:1904)
	at ucar.nc2.grib.GribCollectionBuilder.makeFiles(GribCollectionBuilder.java:39)
	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.createIndex(Grib2CollectionBuilder.java:610)
	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.createIndex(Grib2CollectionBuilder.java:435)
	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.readOrCreateIndex(Grib2CollectionBuilder.java:148)
	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.readOrCreateIndexFromSingleFile(Grib2CollectionBuilder.java:76)
	at ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:122)
	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:311)
	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1521)
	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:813)
	at ucar.nc2.NetcdfFile.openInMemory(NetcdfFile.java:719)
	at com.windlogics.dmf.weather.HadoopGribCrackerTest.testFileOpening(HadoopGribCrackerTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

**Comment by JohnLCaron** [comment]
You can just scan the grib file and create grib records in memory, without creating an index

See 

https://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/formats/GribFiles.html

at the end "lower level interface to GRIB".
