### ISSUE TITLE
Fix TDM authentication problem

### ISSUE THREAD

**Issue by dopplershift** [Unidata/thredds#361]
TDM 4.6 doesn't properly authenticate over SSL.

**Comment by lesserwhirls** [comment]
@DennisHeimbigner - I just got around to testing this (sorry for the delay) and it looks like the TDM won't even run using the latest master. I get the following error if I try to execute the jar, even without any arguments (at the very least I'd expect the usage string to be output on the command line):

```
java -jar tdm.jar 
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testDriver2' defined in class path resource [resources/application-config.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'serverNames' threw exception; nested exception is java.lang.IllegalArgumentException: Username may not be null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1514)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:140)
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:84)
	at thredds.tdm.Tdm.main(Tdm.java:453)
Caused by: org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'serverNames' threw exception; nested exception is java.lang.IllegalArgumentException: Username may not be null
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:121)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:75)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1510)
	... 13 more
```
Any thoughts? @JohnLCaron - anything jump out? The change was pretty small to the actual TDM code, but I may be missing something.

Thanks!

**Comment by DennisHeimbigner** [comment]
My current speculation is that the tdm problem is closely associated
with the file
./tdm/src/main/resources/resources/application-config.xml, lines 21-29
But why, I do not know.
=Dennis

**Comment by JohnLCaron** [comment]
TDM needs

resources/application-config.xml

gets put into the jar file when building.

**Comment by JohnLCaron** [comment]
BTW, the TDSMonitor does successfully use authentication, so may be a good
lead on comparing what it does vs TDM.

**Comment by lesserwhirls** [comment]
I tried TdsMonitor today (latest master) and could not connect to anything.
I snagged toolsUI 4.6.1 and everything worked out ok.

**Comment by DennisHeimbigner** [comment]
The jar file I am using does have application-config.xml already in it.
=Dennis
p.s. I can reproduce the problem under Intellij for what it is worth.

**Comment by DennisHeimbigner** [comment]
IN both application-config.xml and Tdm.java, there is a reference to a bean
named testDriver2. Can anyone enlighten me where the code for that bean is to be found?

**Comment by JohnLCaron** [comment]
TdsMonitor fails to work on thredds.ucar.edu, works for some reason on rdavm.ucar.edu.

**Comment by JohnLCaron** [comment]
Not sure what is the problem with TDM. Will try to reproduce it when i can.

**Comment by JohnLCaron** [comment]
Should be some failing unit tests to test the authentication stuff outside TDM.

**Comment by DennisHeimbigner** [comment]
At this point, I do not think the proximate problem is authentication. We need to solve
the failure to read application-config and then see if the authentication problem is still there.
I note that both TestSSH and TestAuth seem to be working, so ordinary https: should be ok.

**Comment by DennisHeimbigner** [comment]
If you edit (master) ./tdm/src/main/resources/resources/application-config.xml
to remove this part:
 <property name="catalog" value="classpath:/resources/indexNomads.xml"/>
    <property name="serverNames">
      <list>
        <value>http://localhost:8080/</value>
      </list>
    </property>
Then everything seems to work ok.
Can anyone confirm.

**Comment by JohnLCaron** [comment]
i think the problem is that you cant execute without command-line
arguments. see the TDM.adoc. Esp you need

-Dtds.content.root.path

**Comment by DennisHeimbigner** [comment]
Agreed, however when I said 'works ok' I meant that the error messages
at that point were of the form "file not found" because of the missing -Dtds.content.root.path
but the internal to spring errors were gone.

**Comment by JohnLCaron** [comment]
not sure what status you have. with -Dtds.content.root.path things work ok for me.

**Comment by DennisHeimbigner** [comment]
ok, I think we can now return to the question of wether tdm is properly
accessing https:, which it looks like it is.
