### ISSUE TITLE
Problems with remote access to NEXRAD Level II data

### ISSUE THREAD

**Issue by dopplershift** [Unidata/thredds#435]
From e-support EMY-911316
```
getSweep 
opendap.dap.DataReadException: Inconsistent array length read: 1165128303 != 1914731274; Reflectivity_HI -- 0:0,0:719,0:1831

******************
Stack trace:
java.io.IOException: opendap.dap.DataReadException: Inconsistent array length read: 1165128303 != 1914731274; Reflectivity_HI -- 0:0,0:719,0:1831
at ucar.nc2.dods.DODSNetcdfFile.readData(DODSNetcdfFile.java:1665)
at ucar.nc2.Variable.reallyRead(Variable.java:907)
at ucar.nc2.Variable._read(Variable.java:892)
at ucar.nc2.Variable.read(Variable.java:703)
at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:557)
at ucar.nc2.dataset.VariableDS._read(VariableDS.java:537)
at ucar.nc2.Variable.read(Variable.java:703)
at ucar.nc2.Variable.read(Variable.java:649)
at ucar.nc2.dt.radial.LevelII2Dataset$LevelII2Variable$LevelII2Sweep.sweepData(LevelII2Dataset.java:466)
at ucar.nc2.dt.radial.LevelII2Dataset$LevelII2Variable$LevelII2Sweep.readData(LevelII2Dataset.java:450)
at ucar.unidata.data.radar.CDMRadarAdapter.getSweep(CDMRadarAdapter.java:3540)
at ucar.unidata.data.radar.CDMRadarAdapter.getData(CDMRadarAdapter.java:1917)
at ucar.unidata.data.radar.RadarDataSource$2.run(RadarDataSource.java:531)
at visad.util.ThreadManager.runInParallel(ThreadManager.java:273)
at visad.util.ThreadManager.runInParallel(ThreadManager.java:245)
at visad.util.ThreadManager.runInParallel(ThreadManager.java:212)
at ucar.unidata.data.radar.RadarDataSource.getDataInner(RadarDataSource.java:544)
at ucar.unidata.data.DataSourceImpl.getData(DataSourceImpl.java:2390)
at ucar.unidata.data.DirectDataChoice.getData(DirectDataChoice.java:332)
at ucar.unidata.data.DataChoice.getData(DataChoice.java:637)
at ucar.unidata.data.DataInstance.getData(DataInstance.java:243)
at ucar.unidata.data.DataInstance.getData(DataInstance.java:207)
at ucar.unidata.data.grid.GridDataInstance.init(GridDataInstance.java:206)
at ucar.unidata.data.grid.GridDataInstance.<init>(GridDataInstance.java:163)
at ucar.unidata.data.grid.GridDataInstance.<init>(GridDataInstance.java:144)
at ucar.unidata.idv.control.GridDisplayControl.doMakeDataInstance(GridDisplayControl.java:293)
at ucar.unidata.idv.control.RadarSweepControl.doMakeDataInstance(RadarSweepControl.java:296)
at ucar.unidata.idv.control.DisplayControlImpl.initializeDataInstance(DisplayControlImpl.java:3278)
at ucar.unidata.idv.control.DisplayControlImpl.setData(DisplayControlImpl.java:3234)
at ucar.unidata.idv.control.PlanViewControl.setData(PlanViewControl.java:664)
at ucar.unidata.idv.control.RadarSweepControl.setData(RadarSweepControl.java:114)
at ucar.unidata.idv.control.PlanViewControl.init(PlanViewControl.java:489)
at ucar.unidata.idv.control.RadarSweepControl.init(RadarSweepControl.java:158)
at ucar.unidata.idv.control.DisplayControlImpl.init(DisplayControlImpl.java:1402)
at ucar.unidata.idv.control.DisplayControlImpl.init(DisplayControlImpl.java:1085)
at ucar.unidata.idv.ControlDescriptor.initControl(ControlDescriptor.java:986)
at ucar.unidata.idv.ControlDescriptor$1.run(ControlDescriptor.java:911)
at ucar.unidata.util.Misc$3.run(Misc.java:1243)
```

I can reproduce easily. Local file opens fine (including ncdump of data using ToolsUI). Opendap and CDMRemote (from both ToolsUI and Python) fail....all with different messages.

**Comment by DennisHeimbigner** [comment]
Bugs like this have popped up periodically and for opendap we have never been able to solve.
I think that trying to solve it thru cdmremote is the way to go since it is a simpler protocol and code base.

**Comment by dopplershift** [comment]
It shouldn't be *that* hard to run down in opendap--it's not transient, it happens with every file I've tried on the server. (Which also makes me believe it's the Level II code, not necessarily the protocol handlers.)

**Comment by DennisHeimbigner** [comment]
If you choose to have me solve it, that is ok.

**Comment by dopplershift** [comment]
So those of you who had commit 182c1ae7c0002f1cfed63447c32b83487a0aaea4 in the "what broke this pool", you win...nothing. So FileCache is the problem. I guess @cwardgar and I need to figure out how to make the Nexrad2 IOSP work with the "fixed" cache.

**Comment by JohnLCaron** [comment]
Just reviewing this.
Looks like exact same problem in CinradIOServiceProvider, which is clearly a clone of Nexrad2.
