### ISSUE TITLE
Write attribute value of type Object[]

### ISSUE THREAD

**Issue by r0perice** [Unidata/thredds#507]
Hello,

I Have troubles writting Attributes in Java (v4.6.4). 

* Who I read the attribute values :

```java
 final boolean isArray = attribute.isArray();
        if (isArray) {
            final Array attrValues = attribute.getValues();
            value = attrValues.copyTo1DJavaArray();
        } else {
            value = attrFirstValue;
        }
```
* How I write the attribute :

```java
attr = new Attribute(name, Array.factory(values));
writer.addVariableAttribute(variable, attr);
```
This works with `short[]` and `byte[]` but I have a problem with `Object[]` :

> FAILED: netcdfOutputTest
java.lang.NullPointerException
	at ucar.ma2.Array.**reflectArrayCopyIn**(Array.java:259)
	at ucar.ma2.Array.reflectArrayCopyIn(Array.java:263)
	at ucar.ma2.Array.factory(Array.java:252)

In the method **reflectArratCopyIn()**

```java
static private void reflectArrayCopyIn(Object jArray, Array aa, IndexIterator aaIter) {
    Class cType = jArray.getClass().getComponentType();
    if (cType.isPrimitive()) {
      aa.copyFrom1DJavaArray(aaIter, jArray);  // subclass does type-specific copy
    } else {
      for (int i = 0; i < java.lang.reflect.Array.getLength(jArray); i++)  // recurse
        reflectArrayCopyIn(java.lang.reflect.Array.get(jArray, i), aa, aaIter);
    }
  }
```
The call `jArray.getClass().getComponentType();` returns `null` for `Object[]`.

Is their another method to use in my case ? In fact my `Object[]` is a `String[]` 

Any help will be greatly appreciated :+1: 

Regards,

Robin

**Comment by lesserwhirls** [comment]
Greetings @r0perice,

This is a bug, for sure. The javadoc for `Array.factory` for input of an `Object[]` has a [comment](https://www.unidata.ucar.edu/software/thredds/current/netcdf-java/javadoc/ucar/ma2/Array.html#factory-java.lang.Object-) that says:

```
LOOK: not sure this works for reference types.
```

and, well, sure enough, it doesn't.

Thanks for the detailed report!

**Comment by cwardgar** [comment]
This is related to #600.

**Comment by antoinetran** [comment]
Does anyone know if this is fixed in 4.6.x?
