### ISSUE TITLE
Write EnumTypeDef without annotations

### ISSUE THREAD

**Issue by r0perice** [Unidata/thredds#511]
Hello,

I have troubles trying to write an **EnumTypeDef** wich doesn't have annotations.

I toggle a breakpoint on the following line in my code:
```java
var.getEnumTypedef() 
```
I can see that `annotations` is empty.

![](https://i.imgsafe.org/edde68b.png)

This provokes :

>java.lang.NullPointerException
	at ucar.nc2.jni.netcdf.**Nc4Iosp.createVariable**(Nc4Iosp.java:2433)
	at ucar.nc2.jni.netcdf.Nc4Iosp.createGroup(Nc4Iosp.java:2394)
	at ucar.nc2.jni.netcdf.Nc4Iosp.create(Nc4Iosp.java:2308)

In  **Nc4Iosp.createVariable** there is :
```java
else if(v.getDataType().isEnum()) {
        EnumTypedef en = v.getEnumTypedef();
        UserType ut = (UserType) en.getAnnotation("UserType");  <= This line returns null
        typid = ut.typeid;
        vinfo = new Vinfo(g4, -1, typid);

    }
```

Does every **EnumTypeDef** have this annotation ? Maybe my netcdf4 file is invalid ..

Any help appreciated !

Regards,

Robin

**Comment by DennisHeimbigner** [comment]
The annotation mechanism is internal and is used to hold meta-info
about nodes in the CDM tree. In this case, the enum type def is annotated
with the UserType for the enum when it was opened from the netcdf-c file.
Are you creating a new netcdf-c file using the NC4IOSP?

**Comment by r0perice** [comment]
I am reading the netcdf file using java library and I want to write the same file using the java library too (wich is using jna to load netcdf-c lib).

But for each `Variable var` of my file, `var.getEnumTypedel().getAnnotations()`  is empty wich cause troubles when I try to write a new netcdf file using thoses enums.

**Comment by DennisHeimbigner** [comment]
That is odd. I assume that when you copy, you also create the enum type
in the output file.

**Comment by DennisHeimbigner** [comment]
I am unable to duplicate this error using the following JUnit testcase (imports elided).
Can you modify it to match what you are doing?

public class TestNc4Enum
{
    static final String TESTFILE = "d:/testfilew.nc";
    static final String ENAME = "dessertType";
    static final Map<Integer, String> econsts = new HashMap<>();
    static {
        econsts.put(18, "pie");
        econsts.put(268, "donut");
        econsts.put(3284, "cake");
    }
    private boolean showCompareResults = true;
    private int countNotOK = 0;

    @Before
    public void setLibrary()
    {
        // Ignore this class's tests if NetCDF-4 isn't present.
        // We're using @Before because it shows these tests as being ignored.
        // @BeforeClass shows them as *non-existent*, which is not what we want.
        Assume.assumeTrue("NetCDF-4 C library not present.", Nc4Iosp.isClibraryPresent());
    }

    @Test
    public void testNc4Enum()throws Exception {
        NetcdfFileWriter ncw = NetcdfFileWriter.createNew(NetcdfFileWriter.Version.netcdf4, TESTFILE);
        EnumTypedef ed = new EnumTypedef(ENAME, econsts, DataType.ENUM4);
        Group root = ncw.addGroup(null, null);
        root.addEnumeration(ed);
        try {
            ncw.create(); ncw.close();
        } catch (IOException e) {
            Assert.assertTrue(String.format("ERROR creating file %s%n%s", TESTFILE, e.getMessage()), false);
        }
        NetcdfFile ncr = NetcdfFile.open(TESTFILE);
        ed = ncr.getRootGroup().findEnumeration(ENAME);
        Assert.assertTrue("Enum type not defined: " + ENAME, ed != null);
        Assert.assertTrue("Incorrect enum type name: " + ENAME, ed.getName().equals(ENAME));
        Map<Integer, String> edmap = ed.getMap();
        Assert.assertTrue("Enum type empty", edmap != null && edmap.size() > 0);
        Assert.assertTrue("Enum type size incorrect: " + edmap.size(), edmap.size() == econsts.size());
        for(Map.Entry<Integer, String> entry : edmap.entrySet()) {
            String name = econsts.get(entry.getKey());
            Assert.assertTrue("Enum value missing: " + entry.getValue(), name != null);
            Assert.assertTrue(String.format("Enum mismatch: %d->%s :: %d->%s",
                    entry.getKey(),entry.getValue(),entry.getKey(),name),
                    entry.getValue().equals(name));
        }
        ncr.close();
        File f = new File(TESTFILE);
    }
}

**Comment by r0perice** [comment]
Ok I changed the test to match what I want to do (I'm using TestNG) :

```java
public class TestNc4Enum {

    /** The slf4j LOGGER. */
    private static final org.slf4j.Logger LOGGER = LoggerFactory.getLogger(TestNc4Enum.class);

    static final Map econsts = new HashMap<>();
    static final String ENAME = "dessertType";
    static final String TESTFILE = "target/test-output/TestNc4Enum.nc";

    private final int countNotOK = 0;

    private final boolean showCompareResults = true;
    static {
        econsts.put(18, "pie");
        econsts.put(268, "donut");
        econsts.put(3284, "cake");

    }

    @BeforeClass
    public void initOutputFolder() {
        // create folder
        final File folder = new File("target/test-output/");
        if (!folder.exists()) {
            folder.mkdirs();
        }
    }

    @BeforeClass
    public void loadNetcdfLib() {
        NetcdfOutput.loadNetcdfLib();
    }

    @Test
    public void testNc4Enum() throws Exception {


        final NetcdfFileWriter ncw = NetcdfFileWriter.createNew(NetcdfFileWriter.Version.netcdf4, TESTFILE);
        final EnumTypedef ed = new EnumTypedef(ENAME, econsts, DataType.ENUM4);
        final Group root = ncw.addGroup(null, null);
        root.addEnumeration(ed);

        // add a string-valued variable: char svar(80)
        final Dimension svarLen = ncw.addDimension(null, "svar_len", 80);
        final Variable var = ncw.addVariable(null, "svar", DataType.ENUM4, "svar_len");

        var.setEnumTypedef(ed);

        try {
            ncw.create();
            ncw.close();
        } catch (final IOException e) {
            LOGGER.error("ERROR creating file {}", TESTFILE, e.getMessage());
        }
    }

}

```

When I dump the file I have :  
  
```
netcdf TestNc4Enum.nc {
  types:
    enum dessertType { 'pie' = 18, 'donut' = 268, 'cake' = 3284};

  dimensions:
    svar_len = 80;
  variables:
    enum svar svar(svar_len=80);

}
```

First question. Why `enum svar svar(svar_len=80)` isn't `enum dessertType svar(svar_len=80)` ?

I can reproduce my bug when I comment the line : 
```java
// root.addEnumeration(ed);
```

In input I have this netcdf4 file :
```
netcdf NetcdfOutputTest-input.nc {
  types:
    byte enum boolean { 'false' = 0, 'true' = 1};
    byte enum trilean { 'false' = 0, 'true' = 1, 'undefined' = 2};
    byte enum reference_grid_type { '500m' = 0, '1km' = 1, '2km' = 2};
    byte enum swath_direction_type { 'EastWest' = 0, 'WestEast' = 1};

  dimensions:
    number_of_l0_channels = 17;
    number_of_l1c_channels = 4;
    number_of_reference_grids = 2;
  variables:
    enum boolean timeliness_non_nominal;
      :long_name = "comment";

    String l1c_channels_present(number_of_l1c_channels=4);
      :long_name = "comment";

}
```

The bug appears when I write `    enum boolean timeliness_non_nominal;
      :long_name = "comment";`

Console output :
>java.lang.NullPointerException
	at ucar.nc2.jni.netcdf.Nc4Iosp.createVariable(Nc4Iosp.java:2433)
	at ucar.nc2.jni.netcdf.Nc4Iosp.createGroup(Nc4Iosp.java:2394)
	at ucar.nc2.jni.netcdf.Nc4Iosp.create(Nc4Iosp.java:2308)

**Comment by r0perice** [comment]
Ok I find the problem, I created a new EnumTypeDef object instead of using the object added to the group. There is what I did to solve that.

```java
        if (dataType.isEnum()) {
            variable = writer.addVariable(group, name, dataType, shape);

            for (final EnumTypedef etd : group.getEnumTypedefs()) {
                if (enumName.equals(etd.getShortName())) {
                    variable.setEnumTypedef(etd);
                }
            }

            Group parent = group.getParentGroup();
            while (parent != null) {
                for (final EnumTypedef etd : parent.getEnumTypedefs()) {
                    if (enumName.equals(etd.getShortName())) {
                        variable.setEnumTypedef(etd);
                    }
                }
                parent = parent.getParentGroup();
            }
        }
```

But know I have a problem (same as #516) when I do :
```java
arr = MAMath.convert(Array.factory(value), var.getDataType());
```
