### ISSUE TITLE
Support variables with multiple VLEN dimensions

### ISSUE THREAD

**Issue by cwardgar** [Unidata/thredds#567]
From [the mailing list](http://www.unidata.ucar.edu/mailing_lists/archives/netcdf-java/2016/msg00050.html). NetCDF-Java fails to properly read data from variables that contain multiple VLEN dimensions.

foo.cdl
````
netcdf multi_vlen {
  types:
    int(*) vlenI_t ;
    vlenI_t(*) a_vlenI_t ;
  dimensions:
    dimA = 3 ;
  variables:
    vlenI_t simpleVar(dimA) ;
    a_vlenI_t myVar(dimA) ;

  data:
    simpleVar = 
      {1, 2, 3},
      {1, 2, 3, 4}, 
      {1, 2, 3, 4, 5} ;
    myVar =
    {
      {1},
      {1, 2}
    },
    {
      {1, 2, 3},
      {1, 2, 3, 4}, 
      {1, 2, 3, 4, 5}
    },
    {
      {1, 2, 3, 4, 5, 6}, 
      {1, 2, 3, 4, 5, 6, 7},
      {1, 2, 3, 4, 5, 6, 7, 8}, 
      {1, 2, 3, 4, 5, 6, 7, 8, 9}, 
      {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
    } ;
}
````
We can generate the file and read it back in using the C library:
````
[cwardgar@MacBook-Pro ~/Downloads]
$ ncgen -b -k nc4 -o foo.nc4 foo.cdl
[cwardgar@MacBook-Pro ~/Downloads]
$ ncdump foo.nc4
netcdf foo {
types:
  int(*) vlenI_t ;
  vlenI_t(*) a_vlenI_t ;
dimensions:
	dimA = 3 ;
variables:
	vlenI_t simpleVar(dimA) ;
	a_vlenI_t myVar(dimA) ;
data:

 simpleVar = {1, 2, 3}, {1, 2, 3, 4}, {1, 2, 3, 4, 5} ;

 myVar = {{1}, {1, 2}}, {{1, 2, 3}, {1, 2, 3, 4}, {1, 2, 3, 4, 5}}, 
    {{1, 2, 3, 4, 5, 6}, {1, 2, 3, 4, 5, 6, 7}, {1, 2, 3, 4, 5, 6, 7, 8}, {1, 2, 3, 4, 5, 6, 7, 8, 9}, {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}} ;
}
````
However, when we try to read it in using NetCDF-Java, there are problems.
````java
        File file = new File("/Users/cwardgar/Downloads/foo.nc4");
        try (NetcdfFile ncFile = NetcdfFile.open(file.getAbsolutePath())) {
            System.out.println(ncFile);
            System.out.println("simpleVar: " + ncFile.findVariable("simpleVar").read());
            System.out.println("myVar: " + ncFile.findVariable("myVar").read());
        }
````
First, using `H5iosp`
````
netcdf /Users/cwardgar/Downloads/foo.nc4 {
  dimensions:
    dimA = 3;
  variables:
    int myVar(dimA=3, *);

    int simpleVar(dimA=3, *);

}

simpleVar: 1 2 3  1 2 3 4  1 2 3 4 5  
myVar: 1 2096  3 2096 0  6 2096 0 13 7  
````
`simpleVar` behaves as expected. However, the declaration of `myVar` is wrong, as well as its data.

Second, using `Nc4Iosp`:
````
netcdf /Users/cwardgar/Downloads/foo.nc4 {
  dimensions:
    dimA = 3;
  variables:
    int simpleVar(dimA=3, *);

    int myVar(dimA=3, *);

}

simpleVar: 1 2 3  1 2 3 4  1 2 3 4 5  

Exception in thread "main" java.lang.UnsupportedOperationException: Vlen type 32 = ucar.nc2.jni.netcdf.Nc4Iosp$ConvertedType@7fbe847c
	at ucar.nc2.jni.netcdf.Nc4Iosp.readVlen(Nc4Iosp.java:1956)
	at ucar.nc2.jni.netcdf.Nc4Iosp.readDataAll(Nc4Iosp.java:1711)
	at ucar.nc2.jni.netcdf.Nc4Iosp.readData(Nc4Iosp.java:1483)
	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:2021)
	at ucar.nc2.Variable.reallyRead(Variable.java:874)
	at ucar.nc2.Variable._read(Variable.java:845)
	at ucar.nc2.Variable.read(Variable.java:723)
	at Foo.main(Foo.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
````
Even worse. The Javadoc for `Nc4Iosp.readVlen()` notes that the method "only works for atomic base types; structures will fail." Actually, it would seem that a VLEN of *any* user-defined type will fail, including another, nested VLEN.

I'm not exactly sure where the failure is here. Could be `H5iosp`; could be `Nc4Iosp`; could be the CDM. Or maybe it's some combination of the three. What's clear is that no support for this sort of construct has even been attempted.

**Comment by cwardgar** [comment]
I think that this is a symptom of a larger problem: the CDM doesn't really support NetCDF-4's user-defined types and we're kind of just faking it right now. The sham is revealed whenever we try to nest them.

I believe that #273, #298, and [this mailing list thread](https://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg12544.html) are all related.

**Comment by cwardgar** [comment]
I found some [documentation of this](http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/CDM/Netcdf4.html). Scroll down to "Internal Notes".

It claims:
````
int(3,*,*) returns ArrayObject(3) with ArrayObject(*) inside with ArrayInt(*) inside.
````
but I'm actually getting an `ArrayObject(3)` with just one `ArrayObject(*)` inside (no further nesting). And the data's still nonsense. Maybe these are just notes about how the feature *could* be implemented.
