### ISSUE TITLE
Array.factory(Object) cannot handle String[]

### ISSUE THREAD

**Issue by cwardgar** [Unidata/thredds#600]
From the [mailing list](http://www.unidata.ucar.edu/mailing_lists/archives/netcdf-java/2016/msg00068.html). Executing:
```java
String tsar[] = new String[]{"one", "two", "three"};
Array.factory(tsar);
```
results in:
```
Exception in thread "main" java.lang.NullPointerException
	at ucar.ma2.Array.reflectArrayCopyIn(Array.java:259)
	at ucar.ma2.Array.reflectArrayCopyIn(Array.java:263)
	at ucar.ma2.Array.factory(Array.java:252)
	at Foo.main(Foo.java:10)
```
I think we can add some special-case handling for String[] in `Array.reflectArrayCopyIn()` to fix this.

**Comment by JohnLCaron** [comment]
Extensively refactored in 5.0 esp for unsigned types, now:

  static public Array makeFromJavaArray(Object javaArray);

but not sure if it works there.

But this should work:

Array.factory(DataType.STRING , shape, stringArray);
