### ISSUE TITLE
Assertion errors in Nc4Iosp.java

### ISSUE THREAD

**Issue by LupusUmbrae** [Unidata/thredds#650]
Hello,

A couple of times now I've had to argue with assertions during tests to prevent the Nc4Iosp.java from throwing assertion errors such as this:

```
java.lang.AssertionError
	at ucar.nc2.jni.netcdf.Nc4Iosp.writeData(Nc4Iosp.java:2808)
	at ucar.nc2.jni.netcdf.Nc4Iosp.writeData(Nc4Iosp.java:2789)
	at ucar.nc2.NetcdfFileWriter.write(NetcdfFileWriter.java:954)
```

From what i can tell by looking at that [line](https://github.com/Unidata/thredds/blob/v4.6.6/netcdf4/src/main/java/ucar/nc2/jni/netcdf/Nc4Iosp.java#L2808) is that it's just asserting that what i'm writing is the same size as the section i've asked it to write. As it turns out i'd made a mistake in that :(, however there is no message and no clue initially whats gone wrong.

Asking maven to download the source/javadocs for the netcdfAll artifact doesn't work so I end up having to use GitHub to search the source code for what might be wrong.

Would it be possible to at least add a message to *every* assert in the Nc4Iosps.java to point people at their mistakes?

As a side request, could you publish the source and javadocs to maven as well please

**Comment by cwardgar** [comment]
I agree with you about unhelpful assertions. In fact, I think I've had difficulty with that exact assertion myself. It should really be an exception.

We don't publish source/javadoc for netcdfAll, but we do for its component modules, which are `cdm`, `clcommon`, `bufr`, `grib`, `netcdf4`, `opendap`, and `httpservices`. Why not just use one or all of those in your Maven build, as described [here](http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/BuildDependencies.html)?

**Comment by LupusUmbrae** [comment]
Thanks, will switch from NetcdfAll to the specific ones i need (hadn't come across that page before)
