### ISSUE TITLE
reading grib returns error java.lang.NullPointerException

### ISSUE THREAD

**Issue by jbadag** [Unidata/thredds#834]
Hi, 
I'm working with subseasonal data of ECMWF. I download the data of the TIGGE page for the NCEP model, for real time data:
(http://apps.ecmwf.int/datasets/data/s2s-realtime-instantaneous-accum-kwbc/levtype=sfc/type=cf/)

and reforecasts data:
(http://apps.ecmwf.int/datasets/data/s2s-reforecasts-instantaneous-accum-kwbc/levtype=sfc/type=cf/). 

I open and process this gribs data files using matlab 2017 with nctoolbox 1.1.3 and i don't have any problem with real time data, but when I try to open the reforecasts data gribs, I get a java error (see below).

On the other hand I tried to view the file using the panoply software and got the same error message (see attached). 
![unnamed](https://cloud.githubusercontent.com/assets/16575671/25910092/96b8fc1a-3585-11e7-83aa-e664d2c3f01e.png)

An example file with which I have problems can be downloaded from here:
https://www.dropbox.com/s/j4mtsk0jsj2jiz2/20101229_31.grib?dl=0

My Java version is:
Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

My Operative System is: 
Microsoft WIndows 10 Pro

Does anyone have an idea what could be causing the problem?

Error using ncdataset (line 97)
Failed to open C:

Error in cfdataset (line 59)
obj = obj@ncdataset(url);

Error in ncgeodataset (line 74)
obj = obj@cfdataset(url);

Error in bias_NCEP (line 11)
nc=ncgeodataset(archivo_con);

Caused by:
Error using ncdataset (line 81)
Java exception occurred:
java.lang.NullPointerException

	at ucar.nc2.grib.grib2.Grib2Rectilyser.cdmVariableHash(Grib2Rectilyser.java:453)

	at ucar.nc2.grib.grib2.Grib2Rectilyser.make(Grib2Rectilyser.java:101)

	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.makeAggregatedGroups(Grib2CollectionBuilder.java:489)

	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.createIndex(Grib2CollectionBuilder.java:414)

	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.readOrCreateIndex(Grib2CollectionBuilder.java:157)

	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.readOrCreateIndexFromSingleFile(Grib2CollectionBuilder.java:77)

	at ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:123)

	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:310)

	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1499)

	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:887)

	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:496)

	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:693)

	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)

	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)

	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)

	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)

**Comment by lesserwhirls** [comment]
It looks like we are missing Product Definition Section (PDS) [Template 61](http://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_table4-0.shtml):

| template | description |
|----------|------------|
| 61 | Individual Ensemble Reforecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval (see [Template 4.61](http://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_temp4-61.shtml)) |

`ucar.nc2.grib.grib2.Grib2Pds` will need to be extended to understand the file. Template 61 is very similar to Template 11, so I have hopes it won't be too difficult. However, I'm not sure when I will have a chance to implement this, and then there is getting it back into Matlab, which we do not have control over.

**Comment by msdsoftware** [comment]
Not that I want to muddy the waters, but I'm not sure where @jbadag's stack trace comes from, unless perhaps he's using an older version of Panoply.

Using my devo copy with NJ 4.6.10, then when trying to open the sample dataset from the Dropbox link, I get that the exception occurs in `Grib2Customizer.factory`. Specifically, Panoply calls acquireDataset on the GRIB file and gets:

```
IOException opening dataset: java.io.IOException: java.lang.NullPointerException
java.io.IOException: java.lang.NullPointerException
	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:427)
	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:755)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:427)
	at ucar.nc2.dataset.NetcdfDataset.acquireDataset(NetcdfDataset.java:528)
	at ucar.nc2.dataset.NetcdfDataset.acquireDataset(NetcdfDataset.java:505)
	at gov.nasa.giss.data.nc.NcDataset.<init>(NcDataset.java:114)
	... [various Panoply methods] ...
Caused by: java.lang.NullPointerException
	at ucar.nc2.grib.grib2.table.Grib2Customizer.factory(Grib2Customizer.java:63)
	at ucar.nc2.grib.collection.Grib2CollectionBuilder.makeGroups(Grib2CollectionBuilder.java:123)
	at ucar.nc2.grib.collection.GribCollectionBuilder.createMultipleRuntimeCollections(GribCollectionBuilder.java:150)
	at ucar.nc2.grib.collection.GribCollectionBuilder.createIndex(GribCollectionBuilder.java:138)
	at ucar.nc2.grib.collection.GribCdmIndex.openGribCollectionFromDataFile(GribCdmIndex.java:780)
	at ucar.nc2.grib.collection.GribCdmIndex.openGribCollectionFromDataFile(GribCdmIndex.java:764)
	at ucar.nc2.grib.collection.GribCdmIndex.openGribCollectionFromRaf(GribCdmIndex.java:734)
	at ucar.nc2.grib.collection.GribIosp.open(GribIosp.java:213)
	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1560)
	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:835)
	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:424)
	... 14 more
```

**Comment by jbadag** [comment]
Hi,
I'm using python with the pygrib package

**Comment by lesserwhirls** [comment]
No progress as of yet @EQuedi. However, I will get it on the list for our next release. Sorry for the delay.

**Comment by cofinoa** [comment]
@lesserwhirls I have made a PR with support for template 61. 

You were right about using template 11.

**Comment by cofinoa** [comment]
@EQuedi, 

The nctoolbox it's using the netcdf-java version 4.3.23, basically because it needs to be compiled for java 1.6 to make it compatible with, at least, Matlab 2008. 

Because you are usin Matlab 2017, the JVM version it's 1.7 and you can compile version netcd-java v4.6.11. 

Checkout from my fork:
```
git clone https://github.com/cofinoa/thredds.git thredds
cd thredds
git checkout Support_GRIB2_PDS_Template_61
./gradlew assemble
```

From here you can try 2 things in the `nctoolbox`. 
1. at the java directory replace the `grib-4.3.23.jar` by the `grib-4.6.12-SNAPSHOT.jar` that has been generated at the `thredds/grib/build/libs/`. Probably this is not working because the mix of versions, then try next
1. replace **all** jars at `nctoolbox/java` directory by the jar `netcdfAll-4.6.12-SNAPSHOT.jar` at the `thredds/build/libs`

Please let us know how that works answering to this issue. 

It may be it's better to open a issue at the [nctoolbox](/nctoolbox/nctoolbox)

**Comment by EQuedi** [comment]
Following your instructions, it is working so far, no more missing template 61 issue here.

Thanks for your help! @cofinoa , @lesserwhirls .

**Comment by cofinoa** [comment]
@Equedi, which version has just worked? replicing just only the grib.jar or all the jars?

**Comment by EQuedi** [comment]
I have replaced all jars in the nctoolbox/java for the two you have indicated (-SNAPSHOT ones). So i left the two jars in the folder (i can see now it was one or another substitution, my mistake). There is any problem doing this?

I had to install java version Java SE 8u161/ 8u162 ( Java 9. had trouble with some 'tools.jar')

So far i'm beeing able to open some S2S reforecast data with no template 61 issue.
